### ISSUE TITLE
Module missing in chapter08

### ISSUE THREAD

**Issue by virsto** [PacktPublishing/Hands-On-Genetic-Algorithms-with-Python#1]
In:   01-hyperparameter-tuning-grid.py 
...
...
`from evolutionary_search import EvolutionaryAlgorithmSearchCV`

gives the following error: 
builtins.ModuleNotFoundError: No module named 'evolutionary_search'

**Comment by EyalWirsansky** [comment]
Hey @virsto,

**evolutionary_search** is a module within the **sklearn-deap** library described in the chapter.

As mentioned in the section '**Hyperparameter Tuning**', you can install this library as follows:
`pip install sklearn-deap`

More details about this library can be found here:
https://github.com/rsteca/sklearn-deap

Please let me know if this solved the issue.

Best Regards,
Eyal
