### ISSUE TITLE
0-1 Knapsack - applying greedy heuristic

### ISSUE THREAD

**Issue by bijoythomas** [PacktPublishing/Hands-On-Genetic-Algorithms-with-Python#2]
The genotype to phenotype mapping based on the ordered inclusion can result in suboptimal solutions especially when you have an item with a weight that's close to the knapsack capacity and a value that is very high. 

In the example, if you change the book's weight to say 395 and value to 10,000, the optimal  solution (book+socks=10,050) must include the book. But since it is the last item, the chances of all items before it being '0' is very slim and the book will never get selected.

A better approach might be to order the initial set of items based on a simple & widely known greedy heuristic - the ratio of value to weight.

**Comment by EyalWirsansky** [comment]
Good point! You are welcome to write a separate program where the solution uses your approach (e.g. 01-solve-knapsack-with-init.py), and upload it as a pull request. 
Keep in mind, though, that the GA is still not guaranteed to always find the optimal solution.

Best Regards,
Eyal

**Comment by bijoythomas** [comment]
> Good point! You are welcome to write a separate program where the solution uses your approach (e.g. 01-solve-knapsack-with-init.py), and upload it as a pull request.
> Keep in mind, though, that the GA is still not guaranteed to always find the optimal solution.
> 
> Best Regards,
> Eyal

Thank you Eyal. I have raised a PR to update the general knapsack 0-1 class itself since this is an overall improvement to the GA algorithm.

**Comment by EyalWirsansky** [comment]
Hi @bijoythomas!
Following your suggestions for improvements, I added a new folder, Feedback-and-Improvements, to the original repo.
This folder will serve as a platform for readers like you to suggest changes, improvements and variations of the original code. These suggestions may be incorporated into future editions of this book.
Each folder underneath starts as a copy of the original corresponding folder, and readers are invited to submit PRs against its files.
Please make your PRs against the corresponding files of this section.
I currently only included Chapter 4, but I will add other chapters as needed.

Best Regards,
Eyal Wirsansky
