### ISSUE TITLE
Issue in VRP route splits

### ISSUE THREAD

**Issue by bijoythomas** [PacktPublishing/Hands-On-Genetic-Algorithms-with-Python#4]
The `getRoutes` method in the `VehicleRoutingProblem` has a bug where is fails to detect an empty route if a separator (a vehicle index) is followed by the index of the central depot at the end of the chromosome. Below is an example:

```
A random Solution for the bayg29 problem with 3 vehicles and depot index of 12
[23, 0, 5, 29, 11, 8, 4, 20, 9, 3, 14, 17, 13, 16, 21, 10, 18, 19, 1, 28, 2, 25, 27, 7, 26, 22, 6, 24, 15, 30, 12]

Notice how the depot index 12 follows the vehicle index 30. In this case `getRoutes` returns
[[23, 0, 5], [11, 8, 4, 20, 9, 3, 14, 17, 13, 16, 21, 10, 18, 19, 1, 28, 2, 25, 27, 7, 26, 22, 6, 24, 15]]
```
It should return
`[[23, 0, 5], [11, 8, 4, 20, 9, 3, 14, 17, 13, 16, 21, 10, 18, 19, 1, 28, 2, 25, 27, 7, 26, 22, 6, 24, 15], []]`

I'd be happy to submit PR to fix this along with a fitness function that minimizes total distance (instead of max distance) and also aims to maximize the vehicle utilization of each vehicle (based on distance travelled)

```
    def getFitnessDistance(self, indices):
        routeDistances = [self.getRouteDistance(route) for route in self.getRoutes(indices)]
        totalDistance = sum(routeDistances)
        avgDistance = totalDistance / self.numOfVehicles
        return totalDistance + sum([abs(avgDistance - dist) for dist in routeDistances])
```
This fitness function yields better results for both the 3 and 6 vehicle variations of the `bayg29` VRP problem.

**Comment by EyalWirsansky** [comment]
Hi @bijoythomas!

You are invited to add your suggestion as a PR to the corresponding file under the new folder "Feedback-and-Improvements".

Best Regards,
Eyal Wirsansky
